name: Release to public ecr

on:
  release:
    types: [created]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Make
        run: sudo apt-get install make

      - name: Login to Public ECR
        run: make login

      - name: Build, tag and push Docker image
        run: make all IMAGE_TAG=${{ github.event.release.name }}